#!/usr/bin/env bash
# Runs once per container: clone the target repo, run `claude -p` headless,
# and if it produced changes, push a branch and open a PR. Never merges
# anything itself (PLAN.md: "Never auto-merge" — existing CI plus human
# review own everything past this point).
set -euo pipefail

: "${TARGET_REPO:?set TARGET_REPO, e.g. owner/repo}"
: "${TASK_PROMPT:?set TASK_PROMPT}"
: "${GITHUB_TOKEN:?set GITHUB_TOKEN}"
export GH_TOKEN="$GITHUB_TOKEN"

# Either credential authenticates claude -p; it picks whichever is set.
# CLAUDE_CODE_OAUTH_TOKEN (from `claude setup-token`, run once on a machine
# with a browser) bills against a Claude Pro/Max/Team/Enterprise
# subscription instead of pay-per-token API usage — see task/README.md.
export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
export CLAUDE_CODE_OAUTH_TOKEN="${CLAUDE_CODE_OAUTH_TOKEN:-}"
if [[ -z "$ANTHROPIC_API_KEY" && -z "$CLAUDE_CODE_OAUTH_TOKEN" ]]; then
  echo "set ANTHROPIC_API_KEY or CLAUDE_CODE_OAUTH_TOKEN" >&2
  exit 1
fi

task_id="${TASK_ID:-$(date +%Y%m%d%H%M%S)}"
base_branch="${BASE_BRANCH:-}"
git_author_name="${GIT_AUTHOR_NAME:-rbox-agent}"
git_author_email="${GIT_AUTHOR_EMAIL:-rbox-agent@users.noreply.github.com}"
out_dir="${RBOX_OUTPUT_DIR:-/home/agent/output}"
mkdir -p "$out_dir"

log() { printf '[rbox-task %s] %s\n' "$task_id" "$*" >&2; }

write_summary() {
  jq -n \
    --arg status "$1" \
    --arg repo "$TARGET_REPO" \
    --arg branch "${branch:-}" \
    --arg pr_url "${pr_url:-}" \
    --arg detail "${2:-}" \
    '{status: $status, repo: $repo, branch: $branch, pr_url: $pr_url, detail: $detail}' \
    > "$out_dir/summary.json"
}

git config --global user.name "$git_author_name"
git config --global user.email "$git_author_email"
git config --global init.defaultBranch main

log "cloning $TARGET_REPO"
git clone "https://x-access-token:${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git" repo
cd repo

if [[ -n "$base_branch" ]]; then
  git checkout "$base_branch"
fi

branch="rbox/task-${task_id}"
git checkout -b "$branch"

log "running claude -p (this is the untrusted step: repo content + prompt drive tool calls)"
claude_args=(-p "$TASK_PROMPT" --dangerously-skip-permissions --output-format json)
if [[ -n "${MAX_TURNS:-}" ]]; then
  claude_args+=(--max-turns "$MAX_TURNS")
fi

set +e
claude "${claude_args[@]}" >"$out_dir/result.json"
claude_status=$?
set -e

if [[ $claude_status -ne 0 ]]; then
  log "claude exited $claude_status, not opening a PR"
  write_summary "claude_failed" "claude -p exited $claude_status"
  exit "$claude_status"
fi

if [[ -z "$(git status --porcelain)" ]]; then
  log "no changes produced, nothing to push"
  write_summary "no_changes"
  exit 0
fi

log "changes detected, committing and pushing"
git add -A
git commit -m "$(cat <<EOF
rbox: ${TASK_PROMPT}

Generated by headless Claude Code (rbox task ${task_id}), unreviewed.
EOF
)"
git push -u origin "$branch"

pr_title="${PR_TITLE:-rbox: ${TASK_PROMPT}}"
pr_body="$(cat <<EOF
Automated change from an rbox headless Claude Code task. Nothing here has
been reviewed by a human yet — treat it like any other proposed change.

**Prompt given to the agent:**

> ${TASK_PROMPT}

Task ID: \`${task_id}\`
EOF
)"

gh_args=(pr create --repo "$TARGET_REPO" --title "$pr_title" --body "$pr_body" --head "$branch")
if [[ -n "$base_branch" ]]; then
  gh_args+=(--base "$base_branch")
fi

pr_url="$(gh "${gh_args[@]}")"
log "opened $pr_url"
write_summary "pr_opened"
echo "$pr_url" > "$out_dir/pr_url.txt"
