#ENC[AES256_GCM,data:fcoLFM8cVrIUmVrztmk3vd+r5n6C3talECa7JYewxgdE0ALyY5Odd1Kr9Ys3S65CpWketkrOpvr3gg==,iv:rUs1oKfP+jngTWUG13wrWZ5RwgG6mflblYx5t/jyHhY=,tag:7Yi92fSDz01sgnBQmAN9/g==,type:comment]
#
#ENC[AES256_GCM,data:J0kZEU7hbpAm0pe8eJhxgNC+wXWYXadvQR8YTbWLwQ/OvWlLlD6k4v8AZIgY7MlmrpZOxyXNgECStWFq4iFw/Roy3w==,iv:B2gw1YbjPedAKnlF79jsjMXYqNmxUDerTjkkkqmiZFs=,tag:5Bd4ON1vGgTg6pIHy7nwng==,type:comment]
#ENC[AES256_GCM,data:lP3vxBBFia3mqnc11TZhUYPbn7Wj1qcl68tnDmfDxEMb9tUB3PKLlO71DQ==,iv:vMNEBtfM0I+OPvc7BSNttI2FsLoMcUNct/vQOzc97MM=,tag:cOnotJQSct8dK1S0cSl2gA==,type:comment]
#
#ENC[AES256_GCM,data:eYlUkfNZGUPA+IF3nwc1CVr3t5kExgTP9S0dMusta1binf536Ql1,iv:Fk2P8sbYCRc6LBWJCojRH+WxXwXS8hs0VJWKJi46hao=,tag:xl4k72T/weZtT7EVQGaabg==,type:comment]
#ENC[AES256_GCM,data:yu6LGKbhgFejQ9M1P3ZD49xo+djY1K4=,iv:1olPNozRrMs/eHQn12uphIAxFTqwt1JOR/D8UA7k6eE=,tag:8291VBsilbSWVLEJPfXdfg==,type:comment]
#ENC[AES256_GCM,data:jZc7fBWWiUiBDgLEoAyhkSmA6mBm2GcXfy5NbThC8AUbR+wAlSKyV+7e,iv:LTsJ0ONp60pLT+pYz2tE4fjy3YAbiCFZ1gFa3G7C1v0=,tag:5nmrUiZ/JgW+l1dvCX8pwA==,type:comment]
#ENC[AES256_GCM,data:ytPoulAYbwm020Y/fyGXMa6y,iv:c6/IYSh5sSsXT4LQKUicgOOZlfqzgAJUrCA+uuSRdHg=,tag:BvonFOcaOfaHXrAl0Z9jmw==,type:comment]
#
#ENC[AES256_GCM,data:I8qDOHqOLDytS0YgasTF8byooEMvHnJaz4mDouMGwkMjLaSTSGBu8sBXjfGNeuyFmcC0L2qaAgmgE10N967mhg==,iv:HyJZ2LyNpmu5WasOPkwOJLGa1iVJU96kY2lE7hHsXTM=,tag:mlFT4Q/r4d/TsWjrBAb0tQ==,type:comment]
#ENC[AES256_GCM,data:oivVE3+UpcXGsWWB6JAvVQaHa0Hr89MMG/pKntZnCAPzqdk157ZK/a/3kZXgFou/fWn/cq/Nh1Q+rcmLiaBjKQ==,iv:fHbE//OhzKbntiO3Y5BMDmmRXtbW0/b2NywseX+84fI=,tag:83lKwRmGdY6nzRN4hh7hNQ==,type:comment]
HCLOUD_TOKEN: ENC[AES256_GCM,data:Kxqrj603Rj+B1AjbVDhC6QMRpwJRzHhJZoxHMrrRu8T3pyRSNez7YWzQXGKhLnd4Od1/k15r6BfbD8gaiQJvLg==,iv:ZkLPgWlfbjSHuRsBvpIZxIo9Betgv2wcBl4scQsKGF0=,tag:CFmmcbrS1EF/78ebAUi4vA==,type:str]
AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:r+2T9J5NWQQBbfcOgjRdDBE4BW6XuP95u/JvC5JTqk8=,iv:r3vZtfl8navsSt+FlYdCaKHsGSpQ+BtkT5W42cQMyLU=,tag:spOSOxfr6F2vunQU2/hKrQ==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9E1xncnuTXi8EvyYmCL2FBmDNER8RTkvvBLrVUS4C4G+e99AEhvWys9jMl3MDv8Qw3yp74WK18P/2WDOSnNLDw==,iv:6x5frG+HV/8w3QhvRX0ORLECGGpexZRVv/XTIVsqpDY=,tag:19PgJDj4NukyjQWp9SP6ng==,type:str]
RBOX_TAILSCALE_IP: ENC[AES256_GCM,data:TsrHoUhLoV1VIAQ=,iv:PqJydulfHxXeCGyfuuLee/g21p44grXWKFk8DNPZ9Hs=,tag:Rs7rgEZ/lQRsy4ci7k2fSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadlpEOTlJOXpPZ2dld1Bw
            d1NuSEFlWFJMeDUzL2o3L1d0KzdTL1huc3lJClBSOWNTVXhiZ2tWVHBxZWNBK2FG
            MDk0TG5LVVFCTVg3OWJNbmRFQUM2ckkKLS0tIHRvekdtWU1uOXUxNE81eit5aGx0
            bXV4ZVNnN2x1cWFUMVpnL0Uwd0FMOUkKOl2pI/lFm8rgL0vlimrdtTvaUr1mlcHE
            MhmWyprcveGP1naHfXyuAvp1tlakL8+gKL7dQ3drFEVTrBDAoQBNRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15e6utlsngr4r9vdm504n6jf74n9mdqc2nedmjwq0keufa4n56c3smmshrr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra1kySksvQ3hxSWZmL2dL
            L044Mk12djJoVmthVXREaCtXZ1JUMjhXUVdvCkF1QThIRUdpZisydGxpMDMrc1Jj
            YjR3eUJBdk14cEM1ZmM5TTdUOTVlSDQKLS0tIDk3c3dXbjdwbE9tRFZlSkxNRDRp
            Qm9LWEorelZJQTBBUFhPbGNMKzRBa2cKqUtfYJJ9M4Tp3Tbb9BuuMaovPu8NvnNs
            hVBwY1gEcZPfxaHCHdOSG4N9RqBQNLnzG/N/y8xm17uKYc70lHsPHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nmxcxychm9qnvxvtmgwj6rhtf9t9t0g0n8mqm9q8q7fkjlqlnslqcmtgzd
    lastmodified: "2026-09-27T08:09:57Z"
    mac: ENC[AES256_GCM,data:c97eYn3cE+9Fsq0smuKq3DHwCLyLmXGzhEPsj0Hr77eaxRcxklnqJ3E17Y5yaqxNz+pITU1mcXS+vxk4QAb37Wi6VAiTJ/9SSaSfwEDEgFi77Bvu8m5w+D25PhIoKP2p/dSU/MCygcuXoj+WPNANqbGk3PTVIACCJxvHar+V6yo=,iv:0VKyqtFMwCkugRK4vfMtqJzked2rN0bgI1fOFRaWRa8=,tag:nkAspO6Crc7QeM/nKbhKgw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
